safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Samuel XIE
host: samuelxiehong.github.io
desc: 数字化浪潮下的极简生活

custom:
    category:
        default: Business
        another: Personal
    categories:
      - name:  default
        title: 企业数字化转型

      - name:  another
        title: 数字化生存

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Samuel XIE
        email: xiehong@icloud.com
        disqus: samuelxiehong                       # Disqus缩略标识
        gcse:                                       # Google自定义搜索标识ID
        github: samuelxiehong                       # GitHub账号
        gravatar: bc1833ccc8d0f1d9d2f0b9a949a3be0a  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
